### ISSUE TITLE
A note does not get deleted when pressing Delete

### ISSUE THREAD

**Issue by kgjika** [ComfortablyCoding/strapi-plugin-notes#4]
https://user-images.githubusercontent.com/96471728/169842437-578f1285-e526-4b38-8706-b92adeb1438e.mp4

> **Background:**

- I was trying to delete a note when I saw that the functionality did not work as expected and I had to refresh the page for the changes to appear.

> **Steps to reproduce:**

On the Notes section:
- Click on the Delete button on one of your notes.
- Look at the note not being deleted.

> **Actual result:**

- The note was not deleted after clicking on Delete. The changes needed a refresh of the page to appear on the screen.

> **Expected result:**

- The note should have been deleted after clicking the Delete button.

**Comment by ComfortablyCoding** [comment]
Closing for now, seems to be same issue/cause as #3
